#!/bin/sh
#
# shadowsocks start/restart/stop shadowsocks
#
# chkconfig: 2345 85 15
# description: start shadowsocks/ssserver at boot time

start(){
        /root/cherryweb/service.sh start
}
stop(){
        /root/cherryweb/service.sh stop
}
restart(){
	/root/cherryweb/service.sh stop
        /root/cherryweb/service.sh start
	
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
restart)
        restart
        ;;
*)
        echo "Usage: $0 {start|restart|stop}"
        exit 1
        ;;
esac
